apiVersion: v1
kind: Namespace
metadata:
  name: storage-demo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: storage-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-persistent
  namespace: storage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-persistent
  template:
    metadata:
      labels:
        app: writer-persistent
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting persistent writer..."
              while true; do
                date >> /data/persistent.log
                sleep 5
              done
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-ephemeral
  namespace: storage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-ephemeral
  template:
    metadata:
      labels:
        app: writer-ephemeral
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting ephemeral writer..."
              while true; do
                date >> /data/ephemeral.log
                sleep 5
              done
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
